### ISSUE TITLE
Docker mountable DB path

### ISSUE THREAD

**Issue by IvoNet** [eclipse-ee4j/starter#101]
if you run the docker image belonging to the generated project it will create the "demo" database in “./opt/payara/payara5/glassfish/domains/domain1/config/jakartaee-cafe-data” which is weird.

I know that it is just a demo but still.

**Comment by jeyvison** [comment]
@IvoNet What would be the expected location?

**Comment by m-reza-rahman** [comment]
What would you suggest as an alternative? Do bear in mind, we need to keep things simple enough to get started - hence the use of the embedded database.

**Comment by IvoNet** [comment]
@m-reza-rahman  and @jeyvison I would expect a location where one could easily create a volume to like `/db`.

But a more relevant discussion IMHO in this context would be.... do we need a db in this archetype? If KISS is the principle here... just remove it from the archetype and create an example elsewhere or in a different archetype.
see discussion item in the mailinglist

Another issue with it is that it is not JTA managed but is running in an application server which is also not as expected or wanted right? one would expect that the app asks for its connection from the application server and not define one itself.
See also discussion in the mailinglist

**Comment by m-reza-rahman** [comment]
Feel free to change the DB path and issue a PR. It should be super easy to do.

I think the best value for a Jakarta EE starter is a complete working example for newcomers. Otherwise, a Jakarta EE Maven project is very trivial and I am not sure what the value proposition of a starter would really be. The user can always just delete and modify the starter to meet their application needs.

With regards to the embedded database and why that is a sensible way to go for the starter, I have already responded in the mailing list.

To be honest, I think we should be making progress towards the more straightforward roadmap items instead of spending too much time revisiting approaches unless there really are significant issues that are clearly problematic. I am not sure for some of these questions there are “right” and “wrong” answers worth spending a lot of time and energy debating.

**Comment by m-reza-rahman** [comment]
Closing this for now. It's out of date.
