### ISSUE TITLE
Can't assign requested address on mac 

### ISSUE THREAD

**Issue by zieshen** [eclipse-ee4j/starter#295]
Getting below error on mac while running Jakarta ee 10 payara micro: mvn clean package payara-micro:start
[2024-03-15T00:53:54.712+0530] [] [SEVERE] [] [com.hazelcast.instance.impl.Node] [tid: _ThreadID=23 _ThreadName=RunLevelControllerThread-1710444234011] [timeMillis: 1710444234712] [levelValue: 1000] [[
  [fe80:0:0:0:701f:c6ff:fef2:57cb]:6900 [development] [5.2.2] Can't assign requested address

**Comment by m-reza-rahman** [comment]
Please provide the exact steps to reproduce.

**Comment by m-reza-rahman** [comment]
In the meantime, I quickly tried to reproduce this using the Web Profile and Java SE 11 from the public UI on Windows. It works fine.

So this is likely an issue with Payara Micro rather than the Starter. Troubleshooting Payara Micro environment/OS issues is beyond the scope of the Starter project. I suggest reaching out to the Payara community or trying another runtime from the Starter.

**Comment by zieshen** [comment]
I tried with open liberty and it's working but failed for Payara. Followed the steps:
1- download the zip generated from https://start.jakarta.ee/ >> jakarta ee10 >> web profile >> SE 11 >> Runtime Payara >> Docker support Yes
2- run `mvn clean package payara-micro:start`. ## using apache-maven-3.6.2
3- got above error.

**Comment by m-reza-rahman** [comment]
Please take this up with the Payara folks. This is out of scope for us.
